conda/analysis3-19.07(11):ERROR:150: Module 'conda/analysis3-19.07' conflicts with the currently loaded module(s) 'conda/analysis3-19.04'
conda/analysis3-19.07(11):ERROR:102: Tcl command execution failed: conflict conda

Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/test.py", line 67, in <module>
    fieldset = ofam_fields(years=years, months=months)
  File "/g/data1a/e14/as3189/OFAM/scripts/main.py", line 92, in timed
    result = method(*args, **kw)
  File "/g/data1a/e14/as3189/OFAM/scripts/main.py", line 134, in ofam_fields
    fieldset = FieldSet.from_b_grid_dataset(filenames, variables, dimensions, 
AttributeError: type object 'FieldSet' has no attribute 'from_b_grid_dataset'
