Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/climo.py", line 42, in <module>
    cdo.mergetime(input= files, output=merge)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.07/lib/python3.6/site-packages/cdo.py", line 369, in get
    cmd.append(' '.join(kwargs["input"]))
TypeError: sequence item 0: expected str instance, PosixPath found
