Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/plx_analysis.py", line 171, in <module>
    particle_density(iexp=args.exp, lon=args.lon, r=args.rr, t=args.time, how=args.method)
  File "/g/data/e14/as3189/OFAM/scripts/plx_analysis.py", line 128, in particle_density
    xids, dss, ds = combine_plx_datasets(cfg.exp_abr[iexp], lon, v=1, r_range=r_range)
  File "/g/data/e14/as3189/OFAM/scripts/main.py", line 429, in combine_plx_datasets
    ds = xr.combine_by_coords(dss, data_vars="minimal")
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.10/lib/python3.8/site-packages/xarray/core/combine.py", line 787, in combine_by_coords
    raise ValueError(
ValueError: Resulting object does not have monotonic global indexes along dimension traj
