Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
Traceback (most recent call last):
  File "/g/data/e14/as3189/OFAM/scripts/base.py", line 119, in <module>
    p.add_argument('-i', '--ifile', default=0, type=int, help='File Index.')
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1373, in add_argument
    return self._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1736, in _add_action
    self._optionals._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1577, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1387, in _add_action
    self._check_conflict(action)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1526, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-20.04/lib/python3.7/argparse.py", line 1535, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -i/--ifile: conflicting option string: -i
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[45355,1],45]
  Exit code:    1
--------------------------------------------------------------------------
